env:
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
rules:
  eqeqeq: off
  semi: off
  "@typescript-eslint/semi": off
  space-before-function-paren: off
  "@typescript-eslint/space-before-function-paren": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/consistent-type-assertions": off
  "@typescript-eslint/explicit-function-return-type": off